# Generated by Django 4.1.7 on 2023-02-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
    ]
