# Generated by Django 4.1.7 on 2023-02-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contact_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Signup',
        ),
    ]
